export const DifficultySelectWidgetDefinition = {
  name: "Container_DifficultyMenu",
  type: "Container",
  position: [0, 0],
  size: [3840, 200],
  anchor: mod.UIAnchor.Center,
  visible: false,
  padding: 0,
  bgColor: [0.2, 0.2, 0.2],
  bgAlpha: 1,
  bgFill: mod.UIBgFill.None,
  children: [
    {
      name: "Container_DifficultyButtons",
      type: "Container",
      position: [0, 0],
      size: [600, 200],
      anchor: mod.UIAnchor.Center,
      visible: true,
      padding: 0,
      bgColor: [0.0314, 0.0431, 0.0431],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.Blur,
      children: [
        {
          name: "Text_Difficulty_SelectYour",
          type: "Text",
          position: [0, 0],
          size: [298.12, 50],
          anchor: mod.UIAnchor.TopCenter,
          visible: true,
          padding: 0,
          bgColor: [0.2, 0.2, 0.2],
          bgAlpha: 1,
          bgFill: mod.UIBgFill.None,
          textLabel: mod.stringkeys.Text_Difficulty_SelectYour,
          textColor: [1, 1, 1],
          textAlpha: 1,
          textSize: 24,
          textAnchor: mod.UIAnchor.Center
        },
        {
          name: "Button_DifficultyEasy",
          type: "Button",
          position: [54.31, 75],
          size: [100, 50],
          anchor: mod.UIAnchor.TopLeft,
          visible: true,
          padding: 0,
          bgColor: [1, 1, 1],
          bgAlpha: 1,
          bgFill: mod.UIBgFill.Solid,
          buttonEnabled: true,
          buttonColorBase: [0.2784, 0.4471, 0.2118],
          buttonAlphaBase: 1,
          buttonColorDisabled: [0.1, 0.1, 0.1],
          buttonAlphaDisabled: 0.5,
          buttonColorPressed: [0.2, 0.2, 0.2],
          buttonAlphaPressed: 1,
          buttonColorHover: [0.4, 0.4, 0.4],
          buttonAlphaHover: 1,
          buttonColorFocused: [0.5, 0.5, 0.5],
          buttonAlphaFocused: 1
        },
        {
          name: "Button_DifficultyMedium",
          type: "Button",
          position: [250, 75],
          size: [100, 50],
          anchor: mod.UIAnchor.TopLeft,
          visible: true,
          padding: 0,
          bgColor: [1, 1, 1],
          bgAlpha: 1,
          bgFill: mod.UIBgFill.Solid,
          buttonEnabled: true,
          buttonColorBase: [1, 0.9882, 0.6118],
          buttonAlphaBase: 1,
          buttonColorDisabled: [0.1, 0.1, 0.1],
          buttonAlphaDisabled: 0.5,
          buttonColorPressed: [0.2, 0.2, 0.2],
          buttonAlphaPressed: 1,
          buttonColorHover: [0.4, 0.4, 0.4],
          buttonAlphaHover: 1,
          buttonColorFocused: [0.5, 0.5, 0.5],
          buttonAlphaFocused: 1
        },
        {
          name: "Button_DifficultyHard",
          type: "Button",
          position: [433.63, 75],
          size: [100, 50],
          anchor: mod.UIAnchor.TopLeft,
          visible: true,
          padding: 0,
          bgColor: [1, 1, 1],
          bgAlpha: 1,
          bgFill: mod.UIBgFill.Solid,
          buttonEnabled: true,
          buttonColorBase: [1, 0.5137, 0.3804],
          buttonAlphaBase: 1,
          buttonColorDisabled: [0.1, 0.1, 0.1],
          buttonAlphaDisabled: 0.5,
          buttonColorPressed: [0.2, 0.2, 0.2],
          buttonAlphaPressed: 1,
          buttonColorHover: [0.4, 0.4, 0.4],
          buttonAlphaHover: 1,
          buttonColorFocused: [0.5, 0.5, 0.5],
          buttonAlphaFocused: 1
        },
        {
          name: "Text_Difficulty_Easy",
          type: "Text",
          position: [54.31, 122.69],
          size: [100, 50],
          anchor: mod.UIAnchor.TopLeft,
          visible: true,
          padding: 0,
          bgColor: [0.2, 0.2, 0.2],
          bgAlpha: 1,
          bgFill: mod.UIBgFill.None,
          textLabel: mod.stringkeys.Text_Difficulty_Easy,
          textColor: [1, 1, 1],
          textAlpha: 1,
          textSize: 24,
          textAnchor: mod.UIAnchor.Center
        },
        {
          name: "Text_Difficulty_Medium",
          type: "Text",
          position: [250, 122.69],
          size: [100, 50],
          anchor: mod.UIAnchor.TopLeft,
          visible: true,
          padding: 0,
          bgColor: [0.2, 0.2, 0.2],
          bgAlpha: 1,
          bgFill: mod.UIBgFill.None,
          textLabel: mod.stringkeys.Text_Difficulty_Medium,
          textColor: [1, 1, 1],
          textAlpha: 1,
          textSize: 24,
          textAnchor: mod.UIAnchor.Center
        },
        {
          name: "Text_Difficulty_Hard",
          type: "Text",
          position: [433.63, 122.69],
          size: [100, 50],
          anchor: mod.UIAnchor.TopLeft,
          visible: true,
          padding: 0,
          bgColor: [0.2, 0.2, 0.2],
          bgAlpha: 1,
          bgFill: mod.UIBgFill.None,
          textLabel: mod.stringkeys.Text_Difficulty_Hard,
          textColor: [1, 1, 1],
          textAlpha: 1,
          textSize: 24,
          textAnchor: mod.UIAnchor.Center
        }
      ]
    }
  ]
}
