export const IntroWidgetDefinition = {
  name: "Container_Intro",
  type: "Container",
  position: [0, 0],
  size: [3840, 500],
  anchor: mod.UIAnchor.Center,
  visible: false,
  padding: 0,
  bgColor: [0.0314, 0.0431, 0.0431],
  bgAlpha: 1,
  bgFill: mod.UIBgFill.Blur,
  children: [
    {
      name: "Text_Intro_Pretitle",
      type: "Text",
      position: [0, -192.11],
      size: [1000, 50],
      anchor: mod.UIAnchor.Center,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.Text_Intro_Pretitle,
      textColor: [1, 0.5137, 0.3804],
      textAlpha: 1,
      textSize: 22,
      textAnchor: mod.UIAnchor.Center
    },
    {
      name: "Text_Intro_Title",
      type: "Text",
      position: [0, -154.37],
      size: [1000, 50],
      anchor: mod.UIAnchor.Center,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.Text_Intro_Title,
      textColor: [1, 1, 1],
      textAlpha: 1,
      textSize: 30,
      textAnchor: mod.UIAnchor.Center
    },
    {
      name: "Text_Intro_Instructions1",
      type: "Text",
      position: [0, -70.9],
      size: [650.03, 114.04],
      anchor: mod.UIAnchor.Center,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.Text_Intro_Instructions1,
      textColor: [1, 1, 1],
      textAlpha: 1,
      textSize: 16,
      textAnchor: mod.UIAnchor.Center
    },
    {
      name: "Text_Intro_Instructions2",
      type: "Text",
      position: [0, 0],
      size: [650.03, 48.86],
      anchor: mod.UIAnchor.Center,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.Text_Intro_Instructions2,
      textColor: [1, 1, 1],
      textAlpha: 1,
      textSize: 16,
      textAnchor: mod.UIAnchor.Center
    },
    {
      name: "Text_Intro_Instructions3",
      type: "Text",
      position: [0, 82.33],
      size: [650.03, 90.03],
      anchor: mod.UIAnchor.Center,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.Text_Intro_Instructions3,
      textColor: [1, 1, 1],
      textAlpha: 1,
      textSize: 16,
      textAnchor: mod.UIAnchor.Center
    },
    {
      name: "Text_Intro_Instructions4",
      type: "Text",
      position: [0, 173.81],
      size: [650.03, 48.86],
      anchor: mod.UIAnchor.Center,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.Text_Intro_Instructions4,
      textColor: [1, 1, 1],
      textAlpha: 1,
      textSize: 18,
      textAnchor: mod.UIAnchor.Center
    }
  ]
};
