export const WaveInfoWidgetDefinition = {
  name: "Container_WaveInfo",
  type: "Container",
  position: [25, 25],
  size: [420, 106],
  anchor: mod.UIAnchor.TopLeft,
  visible: false,
  padding: 5,
  bgColor: [0.2118, 0.2235, 0.2353],
  bgAlpha: 0.6,
  bgFill: mod.UIBgFill.Blur,
  children: [
    {
      name: "Text_WaveInfo_WaveNumber",
      type: "Text",
      position: [20, 8],
      size: [374.72, 50],
      anchor: mod.UIAnchor.TopLeft,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.waveNumberInit,
      textColor: [1, 1, 1],
      textAlpha: 1,
      textSize: 24,
      textAnchor: mod.UIAnchor.CenterLeft
    },
    {
      name: "Text_WaveInfo_WaveDetails",
      type: "Text",
      position: [20, 50],
      size: [367.13, 35],
      anchor: mod.UIAnchor.TopLeft,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.waveDetailsInit,
      textColor: [1, 1, 1],
      textAlpha: 1,
      textSize: 20,
      textAnchor: mod.UIAnchor.CenterLeft
    },
    {
      name: "Text_WaveInfo_WaveTime",
      type: "Text",
      position: [290, 8],
      size: [100, 50],
      anchor: mod.UIAnchor.TopLeft,
      visible: true,
      padding: 0,
      bgColor: [0.2, 0.2, 0.2],
      bgAlpha: 1,
      bgFill: mod.UIBgFill.None,
      textLabel: mod.stringkeys.waveDetailsTime,
      textColor: [0.8353, 0.9216, 0.9765],
      textAlpha: 1,
      textSize: 24,
      textAnchor: mod.UIAnchor.CenterRight
    }
  ]
}
